# Generated by Django 4.2 on 2023-04-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="menu_items/"
            ),
        ),
    ]
